name: run-tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.0]
                laravel: [8.*]
                stability: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 8.*
                      testbench: ^6.6

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        services:
          surrealdb:
            image: surrealcode/surrealdb:latest
            ports:
              - 8000:8000
            env:
              SURREALDB_HOST: localhost
              SURREALDB_PORT: 8000
              SURREALDB_USERNAME: root
              SURREALDB_PASSWORD: root
              SURREALDB_DATABASE: test
              SURREALDB_NAMESPACE: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, libsodium
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ ru
                nner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/pest
